artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/1/541d7bc608ab44b9a832cf567b587a5b/artifacts
end_time: 1653761905500
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 541d7bc608ab44b9a832cf567b587a5b
run_uuid: 541d7bc608ab44b9a832cf567b587a5b
source_name: ''
source_type: 4
source_version: ''
start_time: 1653761064425
status: 3
tags: []
user_id: jxfeng
