artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/1/4fd37f50d06747af8beaf94edcc6bac9/artifacts
end_time: 1653764240053
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 4fd37f50d06747af8beaf94edcc6bac9
run_uuid: 4fd37f50d06747af8beaf94edcc6bac9
source_name: ''
source_type: 4
source_version: ''
start_time: 1653763546388
status: 3
tags: []
user_id: jxfeng
