artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/2/c4b009ab587643538182bc660a8a9ab3/artifacts
end_time: 1653781539946
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c4b009ab587643538182bc660a8a9ab3
run_uuid: c4b009ab587643538182bc660a8a9ab3
source_name: ''
source_type: 4
source_version: ''
start_time: 1653778982636
status: 3
tags: []
user_id: jxfeng
