artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/2/0cbf8159eb1248e3bcf8ed5a2ccbf9d9/artifacts
end_time: 1653776358468
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 0cbf8159eb1248e3bcf8ed5a2ccbf9d9
run_uuid: 0cbf8159eb1248e3bcf8ed5a2ccbf9d9
source_name: ''
source_type: 4
source_version: ''
start_time: 1653773796994
status: 3
tags: []
user_id: jxfeng
