artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/1/cb0c908733c14c33a8a08ac109930361/artifacts
end_time: 1653758774812
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: cb0c908733c14c33a8a08ac109930361
run_uuid: cb0c908733c14c33a8a08ac109930361
source_name: ''
source_type: 4
source_version: ''
start_time: 1653758233663
status: 3
tags: []
user_id: jxfeng
