artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/2/435a805eaf014b468d7e0bba08433802/artifacts
end_time: 1653778980033
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 435a805eaf014b468d7e0bba08433802
run_uuid: 435a805eaf014b468d7e0bba08433802
source_name: ''
source_type: 4
source_version: ''
start_time: 1653776361188
status: 3
tags: []
user_id: jxfeng
