artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/2/016569dd300f4fb4a9314bcd1ac18fc9/artifacts
end_time: 1653789363794
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 016569dd300f4fb4a9314bcd1ac18fc9
run_uuid: 016569dd300f4fb4a9314bcd1ac18fc9
source_name: ''
source_type: 4
source_version: ''
start_time: 1653789265748
status: 4
tags: []
user_id: jxfeng
