artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/2/54cfcb197192419f85548af8e81d3ae7/artifacts
end_time: 1653789263027
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 54cfcb197192419f85548af8e81d3ae7
run_uuid: 54cfcb197192419f85548af8e81d3ae7
source_name: ''
source_type: 4
source_version: ''
start_time: 1653786649470
status: 3
tags: []
user_id: jxfeng
