artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/1/5cd12cbbfc49424782612a93a37064a1/artifacts
end_time: 1653758231053
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 5cd12cbbfc49424782612a93a37064a1
run_uuid: 5cd12cbbfc49424782612a93a37064a1
source_name: ''
source_type: 4
source_version: ''
start_time: 1653756991399
status: 3
tags: []
user_id: jxfeng
