artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/2/fe5dca6245654239872e40438ebd3b18/artifacts
end_time: 1653771234814
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: fe5dca6245654239872e40438ebd3b18
run_uuid: fe5dca6245654239872e40438ebd3b18
source_name: ''
source_type: 4
source_version: ''
start_time: 1653768699320
status: 3
tags: []
user_id: jxfeng
