artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/2/c910e8303df0400089152a7d1b67413a/artifacts
end_time: 1653784096535
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c910e8303df0400089152a7d1b67413a
run_uuid: c910e8303df0400089152a7d1b67413a
source_name: ''
source_type: 4
source_version: ''
start_time: 1653781542699
status: 3
tags: []
user_id: jxfeng
