artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/2/0e566440bb2e454a83b8ade96ce859d7/artifacts
end_time: 1653786646757
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 0e566440bb2e454a83b8ade96ce859d7
run_uuid: 0e566440bb2e454a83b8ade96ce859d7
source_name: ''
source_type: 4
source_version: ''
start_time: 1653784099290
status: 3
tags: []
user_id: jxfeng
