artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/1/f790916349cd41e3a1c6526c404e2c66/artifacts
end_time: 1653763543653
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: f790916349cd41e3a1c6526c404e2c66
run_uuid: f790916349cd41e3a1c6526c404e2c66
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762451351
status: 3
tags: []
user_id: jxfeng
