artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/2/282ae85e7a994ab09fe356ddfc655389/artifacts
end_time: 1653768696589
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 282ae85e7a994ab09fe356ddfc655389
run_uuid: 282ae85e7a994ab09fe356ddfc655389
source_name: ''
source_type: 4
source_version: ''
start_time: 1653766119098
status: 3
tags: []
user_id: jxfeng
