artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/1/46aead2bb73e41f890736765a04f6728/artifacts
end_time: 1653761061700
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 46aead2bb73e41f890736765a04f6728
run_uuid: 46aead2bb73e41f890736765a04f6728
source_name: ''
source_type: 4
source_version: ''
start_time: 1653759523283
status: 3
tags: []
user_id: jxfeng
