artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/1/c51028b1e5d8458f80c3aa76b920fc93/artifacts
end_time: 1653759520606
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: c51028b1e5d8458f80c3aa76b920fc93
run_uuid: c51028b1e5d8458f80c3aa76b920fc93
source_name: ''
source_type: 4
source_version: ''
start_time: 1653758777516
status: 3
tags: []
user_id: jxfeng
