artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/1/0e29bd4349f6455aa2ba15197898632f/artifacts
end_time: 1653764933869
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 0e29bd4349f6455aa2ba15197898632f
run_uuid: 0e29bd4349f6455aa2ba15197898632f
source_name: ''
source_type: 4
source_version: ''
start_time: 1653764242716
status: 3
tags: []
user_id: jxfeng
