artifact_uri: file:///home/jxfeng/code/fintech_qlib/examples/run_all_model_records/2/5498daeb76094ef49ef71d1ad0b5883e/artifacts
end_time: 1653773794353
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 5498daeb76094ef49ef71d1ad0b5883e
run_uuid: 5498daeb76094ef49ef71d1ad0b5883e
source_name: ''
source_type: 4
source_version: ''
start_time: 1653771237430
status: 3
tags: []
user_id: jxfeng
